# Autogenerated! Edit minai_nbs/setup+template.py instead

from setuptools import setup, find_packages

setup(name="minai", 
      author="nblzv", 
      version="0.1.1", 
      packages=find_packages())